In [1]:
import pandas as pd
df = pd.read_csv('sonar_dataset.csv', header=None)
df.head()

0       1       2       3       4       5       6       7       8   \
0  0.0200  0.0371  0.0428  0.0207  0.0954  0.0986  0.1539  0.1601  0.3109   
1  0.0453  0.0523  0.0843  0.0689  0.1183  0.2583  0.2156  0.3481  0.3337   
2  0.0262  0.0582  0.1099  0.1083  0.0974  0.2280  0.2431  0.3771  0.5598   
3  0.0100  0.0171  0.0623  0.0205  0.0205  0.0368  0.1098  0.1276  0.0598   
4  0.0762  0.0666  0.0481  0.0394  0.0590  0.0649  0.1209  0.2467  0.3564   

       9   ...      51      52      53      54      55      56      57  \
0  0.2111  ...  0.0027  0.0065  0.0159  0.0072  0.0167  0.0180  0.0084   
1  0.2872  ...  0.0084  0.0089  0.0048  0.0094  0.0191  0.0140  0.0049   
2  0.6194  ...  0.0232  0.0166  0.0095  0.0180  0.0244  0.0316  0.0164   
3  0.1264  ...  0.0121  0.0036  0.0150  0.0085  0.0073  0.0050  0.0044   
4  0.4459  ...  0.0031  0.0054  0.0105  0.0110  0.0015  0.0072  0.0048   

       58      59  60  
0  0.0090  0.0032   R  
1  0.0052  0.0044   R  
2  0.0095  0.0078   R  
3  0.0040  0.0117   R  
4  0.0107  0.0094   R  

[5 rows x 61 columns]

In [2]:
import warnings
warnings.filterwarnings('ignore')

In [3]:
df.shape

(208, 61)

In [4]:
# check for nan values
df.isna().sum()

0     0
1     0
2     0
3     0
4     0
     ..
56    0
57    0
58    0
59    0
60    0
Length: 61, dtype: int64

In [5]:
df.columns

Index([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
       36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53,
       54, 55, 56, 57, 58, 59, 60],
      dtype='int64')

In [6]:
df[60].value_counts() # label is not skewed

60
M    111
R     97
Name: count, dtype: int64

In [7]:
X = df.drop(60, axis=1)
y = df[60]
y.head()

0    R
1    R
2    R
3    R
4    R
Name: 60, dtype: object

In [8]:
y = pd.get_dummies(y, drop_first=True)
y = y.astype(int)
y.sample(5)

R
29   1
201  0
72   1
60   1
129  0

In [9]:
y.value_counts()

R
0    111
1     97
Name: count, dtype: int64

In [10]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=1)

In [11]:
len(X_train)

156

In [12]:
len(X_test)

52

In [13]:
X_train.head()

0       1       2       3       4       5       6       7       8   \
67   0.0368  0.0403  0.0317  0.0293  0.0820  0.1342  0.1161  0.0663  0.0155   
14   0.0124  0.0433  0.0604  0.0449  0.0597  0.0355  0.0531  0.0343  0.1052   
164  0.0163  0.0198  0.0202  0.0386  0.0752  0.1444  0.1487  0.1484  0.2442   
179  0.0394  0.0420  0.0446  0.0551  0.0597  0.1416  0.0956  0.0802  0.1618   
19   0.0126  0.0149  0.0641  0.1732  0.2565  0.2559  0.2947  0.4110  0.4983   

         9   ...      50      51      52      53      54      55      56  \
67   0.0506  ...  0.0058  0.0091  0.0160  0.0160  0.0081  0.0070  0.0135   
14   0.2120  ...  0.0078  0.0083  0.0057  0.0174  0.0188  0.0054  0.0114   
164  0.2822  ...  0.0027  0.0077  0.0026  0.0031  0.0083  0.0020  0.0084   
179  0.2558  ...  0.0118  0.0146  0.0040  0.0114  0.0032  0.0062  0.0101   
19   0.5920  ...  0.0153  0.0092  0.0035  0.0098  0.0121  0.0006  0.0181   

         57      58      59  
67   0.0067  0.0078  0.0068  
14   0.0196  0.0147  0.0062  
164  0.0108  0.0083  0.0033  
179  0.0068  0.0053  0.0087  
19   0.0094  0.0116  0.0063  

[5 rows x 60 columns]

In [14]:
import tensorflow as tf
from tensorflow import keras

In [15]:
model = keras.Sequential([
    keras.layers.Dense(60, input_dim=60, activation='relu'),
    keras.layers.Dense(30, activation='relu'),
    keras.layers.Dense(15, activation='relu'),
    keras.layers.Dense(1, activation='sigmoid')
])

In [16]:
model.compile(optimizer='adam',metrics=['accuracy'], loss='binary_crossentropy')

In [19]:
model.fit(X_train, y_train, epochs=100, batch_size=10)

Epoch 1/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 1s 789us/step - accuracy: 0.5552 - loss: 0.6836
Epoch 2/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 644us/step - accuracy: 0.5972 - loss: 0.6622
Epoch 3/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 633us/step - accuracy: 0.7501 - loss: 0.6000
Epoch 4/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 663us/step - accuracy: 0.6659 - loss: 0.6127
Epoch 5/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 682us/step - accuracy: 0.6694 - loss: 0.5889
Epoch 6/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 633us/step - accuracy: 0.7793 - loss: 0.5498
Epoch 7/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 598us/step - accuracy: 0.7698 - loss: 0.4848
Epoch 8/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 659us/step - accuracy: 0.7770 - loss: 0.4711
Epoch 9/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 654us/step - accuracy: 0.8310 - loss: 0.4459
Epoch 10/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 642us/step - accuracy: 0.8134 - loss: 0.4037
Epoch 11/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 660us/step - accuracy: 0.8395 - loss: 0.4151
Epoch 12/100
16/16 ━━━━━━━━━━━━━━━━━━━━ 0

In [20]:
## test with test data set
model.evaluate(X_test, y_test)

2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7396 - loss: 1.2085 


[1.0822066068649292, 0.75]

In [21]:
y_pred = model.predict(X_test).reshape(-1)

2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step


In [22]:
y_pred

array([1.21295488e-06, 9.99749720e-01, 9.99393940e-01, 1.02486258e-04,
       1.00000000e+00, 9.97765481e-01, 1.24521121e-01, 1.00000000e+00,
       1.26379367e-04, 1.00000000e+00, 1.43471602e-02, 1.67085708e-03,
       1.78772214e-04, 9.64954903e-04, 1.18984422e-03, 5.53770214e-02,
       9.99798775e-01, 1.62615412e-04, 2.83064451e-02, 9.99999166e-01,
       2.88554984e-05, 1.00000000e+00, 1.16514787e-03, 9.99995232e-01,
       1.72222324e-03, 6.03098124e-06, 1.88543238e-02, 3.52241285e-02,
       1.00000000e+00, 1.52407636e-04, 9.24471974e-01, 3.09719394e-06,
       8.99336413e-02, 2.35669892e-02, 9.99899566e-01, 9.89261746e-01,
       9.99999940e-01, 6.11232519e-01, 9.99999523e-01, 2.90579686e-04,
       4.87841573e-03, 9.66212479e-04, 2.72512496e-01, 1.40204604e-04,
       1.06905005e-04, 3.02054221e-04, 2.24450409e-01, 9.99999285e-01,
       1.60491199e-03, 2.02088580e-02, 3.43755148e-02, 1.32908332e-04],
      dtype=float32)

In [23]:
# round values
import numpy as np
y_pred = np.round(y_pred)
print(y_pred[:10])

[0. 1. 1. 0. 1. 1. 0. 1. 0. 1.]


In [24]:
from sklearn.metrics import confusion_matrix , classification_report

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.71      0.89      0.79        27
           1       0.83      0.60      0.70        25

    accuracy                           0.75        52
   macro avg       0.77      0.74      0.74        52
weighted avg       0.77      0.75      0.74        52



In [25]:
### Model with Dropout Layer
modeld = keras.Sequential([
    keras.layers.Dense(60, input_dim=60, activation='relu'),
    keras.layers.Dropout(0.5),
    keras.layers.Dense(30, activation='relu'),
    keras.layers.Dropout(0.5),
    keras.layers.Dense(15, activation='relu'),
    keras.layers.Dropout(0.5),
    keras.layers.Dense(1, activation='sigmoid')
])

modeld.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

modeld.fit(X_train, y_train, epochs=100, batch_size=8)

Epoch 1/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 673us/step - accuracy: 0.5049 - loss: 0.7375
Epoch 2/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 644us/step - accuracy: 0.5382 - loss: 0.7430
Epoch 3/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 631us/step - accuracy: 0.5748 - loss: 0.7101
Epoch 4/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 609us/step - accuracy: 0.4389 - loss: 0.7213
Epoch 5/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 586us/step - accuracy: 0.5917 - loss: 0.6660
Epoch 6/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 573us/step - accuracy: 0.5803 - loss: 0.6906
Epoch 7/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 568us/step - accuracy: 0.4396 - loss: 0.7202
Epoch 8/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 606us/step - accuracy: 0.4260 - loss: 0.7099
Epoch 9/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 606us/step - accuracy: 0.4500 - loss: 0.7136
Epoch 10/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 593us/step - accuracy: 0.5305 - loss: 0.6729
Epoch 11/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 598us/step - accuracy: 0.6249 - loss: 0.6453
Epoch 12/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0

In [26]:
modeld.evaluate(X_test, y_test)

2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7396 - loss: 0.5625 


[0.5241430997848511, 0.75]

In [27]:
y_pred = modeld.predict(X_test).reshape(-1)
print(y_pred[:10])

# round the values to nearest integer ie 0 or 1
y_pred = np.round(y_pred)
print(y_pred[:10])

2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step
[0.00194168 0.9569685  0.96030384 0.02279611 0.9998048  0.97049683
 0.613471   0.9998454  0.04355523 0.9998837 ]
[0. 1. 1. 0. 1. 1. 1. 1. 0. 1.]


In [28]:
from sklearn.metrics import confusion_matrix , classification_report

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.73      0.81      0.77        27
           1       0.77      0.68      0.72        25

    accuracy                           0.75        52
   macro avg       0.75      0.75      0.75        52
weighted avg       0.75      0.75      0.75        52

